Repository hazelgrove/hazel, pull requests merged in 2021-07, with the labels that each got.

#519 Fix error holes on aps being drawn on function position
  src/hazelcore/CursorPath.re
  src/hazelcore/CursorPath_Exp.re
  src/hazelcore/CursorPath_Pat.re
  src/hazelcore/CursorPath_Typ.re
  src/hazelcore/CursorPath_common.re
  src/hazelweb/model/Program.re
Labels: bug

#518 Fix for issue with creating newline on last line of program
  src/hazelcore/Action_Exp.re
  src/hazelcore/ZExp.re
Labels: enhancement

#523 Automatically treat Ctrl (on non-Macs) and Cmd (on Macs) the same way
  src/hazelcore/Unicode.re
  src/hazelweb/Hazel.re
  src/hazelweb/IsMac.re
  src/hazelweb/ModelAction.re
  src/hazelweb/Update.re
  src/hazelweb/gui/ActionMenu.re
  src/hazelweb/gui/ActionPanel.re
  src/hazelweb/gui/Cell.re
  src/hazelweb/gui/KeyComboAction.re
  src/hazelweb/gui/Page.re
  src/hazelweb/gui/UHCode.re
  src/hazelweb/gui/UHCode.rei
  src/hazelweb/gui/UndoHistoryPanel.re
  src/hazelweb/keyboard/HazelKeyCombos.re
  src/hazelweb/keyboard/HazelKeyCombos.rei
  src/hazelweb/keyboard/Key.re
  src/hazelweb/keyboard/Key.rei
  src/hazelweb/keyboard/KeyCombo.re
  src/hazelweb/keyboard/KeyCombo.rei
  src/hazelweb/keyboard/ModKeys.re
  src/hazelweb/keyboard/ModKeys.rei
  src/hazelweb/keyboard/MoveKey.re
  src/hazelweb/keyboard/MoveKey.rei
  src/hazelweb/model/Model.re
  src/hazelweb/model/Model.rei
Labels: bug, cleanup
