Repository hazelgrove/hazel, pull requests merged in 2022-06, with the labels that each got.

#597 Update Ocaml version to 4.13.1
  .github/workflows/deploy_branches.yml
  INSTALL.md
  README.md
  docs/Updating-OCaml-Version.md
  opam.export
Labels: enhancement

#598 Hazeltext - Backend
  src/hazelcore/layout/DHAnnot.re
  src/hazelcore/layout/DHAnnot.rei
  src/hazelcore/layout/DHDoc.re
  src/hazelcore/layout/DHDoc_Exp.re
  src/hazelcore/layout/DHDoc_Exp.rei
  src/hazelcore/layout/DHDoc_Pat.re
  src/hazelcore/layout/DHDoc_Pat.rei
  src/hazelcore/layout/DHDoc_Typ.re
  src/hazelcore/layout/DHDoc_Typ.rei
  src/hazelcore/layout/DHDoc_Util.re
  src/hazelcore/layout/DHDoc_common.re
  src/hazelcore/layout/DHDoc_common.rei
  src/hazelcore/layout/DHLayout.re
  src/hazelcore/layout/DHLayout.rei
  src/hazelcore/layout/DHSettings.re
  src/hazelcore/layout/Doc_common.re
  src/hazelcore/layout/Doc_common.rei
  src/hazelcore/layout/HTypAnnot.re
  src/hazelcore/layout/HTypAnnot.rei
  src/hazelcore/layout/HTypDoc.re
  src/hazelcore/layout/HTypDoc.rei
  src/hazelcore/layout/HTypLayout.re
  src/hazelcore/layout/HTypLayout.rei
  src/hazelcore/layout/Memo.re
  src/hazelcore/layout/TermShape.re
  src/hazelcore/layout/TermShape.rei
  src/hazelcore/layout/TermSort.re
  src/hazelcore/layout/TermSort.rei
  src/hazelcore/layout/UHAnnot.re
  src/hazelcore/layout/UHAnnot.rei
  src/hazelcore/layout/UHDoc.re
  src/hazelcore/layout/UHDoc_Exp.re
  src/hazelcore/layout/UHDoc_Pat.re
  src/hazelcore/layout/UHDoc_Typ.re
  src/hazelcore/layout/UHDoc_common.re
  src/hazelcore/layout/UHLayout.re
  src/hazelcore/layout/UHLayout.rei
  src/hazelcore/layout/ViewUtil.re
  src/hazelcore/layout/ViewUtil.rei
  src/hazeltext/.ocamlformat
  src/hazeltext/dune
  src/hazeltext/lex.mll
  src/hazeltext/parse.mly
  src/hazeltext/parsing.ml
  src/hazeltext/parsing.mli
  src/hazeltext/print.ml
  src/hazeltext/print.mli
  src/hazeltext/test/dune
  src/hazeltext/test/test.ml
  src/hazelweb/cardstacks/builtins/Examples.re
  src/hazelweb/dune
  src/hazelweb/layout/UHDoc_Exp.re
  src/hazelweb/layout/UHDoc_Pat.re
  src/hazelweb/layout/UHDoc_Typ.re
  src/hazelweb/layout/WeakMemo.re
  src/hazelweb/model/Program.re
  src/hazelweb/model/Settings.re
Labels: needs-polish

#495 refactored Monads module to avoid dynamic dispatch for map
  src/hazelcore/Monads.re
  src/hazelcore/Monads.rei
  src/hazelcore/util/OptUtil.re
Labels: cleanup, in-development, needs-merge
