Repository hazelgrove/hazel, pull requests merged in 2022-08, with the labels that each got.

#677 add www/* to dune source dependencies
  src/web/dune
Labels: haz3l

#678 Gitignore local "_opam/" directory
  .gitignore
Labels: haz3l

#679 Add floating point less-than operator
  src/core/dynamics/elaborator.re
  src/core/lang/Form.re
  src/core/statics/Statics.re
  src/core/statics/Term.re
Labels: haz3l

#680 Recursive let bindings
  src/core/dynamics/elaborator.re
  src/core/lang/Form.re
  src/core/statics/Statics.re
Labels: haz3l

#717 Haz3l N-tuples + N-ary holes
  src/core/dynamics/elaborator.re
  src/core/lang/Form.re
  src/core/lang/Molds.re
  src/core/statics/MakeTerm.re
  src/core/statics/Statics.re
  src/core/statics/Term.re
  src/core/statics/Typ.re
  src/core/zipper/action/Indicated.re
  src/web/Example.re
  src/web/Model.re
  src/web/view/CtxInspector.re
  src/web/view/CursorInspector.re
  src/web/view/Deco.re
  src/web/view/Type.re
Labels: in-development, haz3l

#675 Mouse input for movement and selection
  src/core/zipper/action/Caret.re
  src/core/zipper/action/Move.re
  src/core/zipper/action/Perform.re
  src/web/Model.re
  src/web/Update.re
  src/web/view/Editor.re
  src/web/view/Page.re
  src/web/www/style.css
Labels: haz3l

#656 Move evaluation to web worker
  .github/workflows/deploy_branches.yml
  Makefile
  opam.export
  src/hazelcore/dynamics/DHExp.re
  src/hazelcore/dynamics/DHExp.rei
  src/hazelcore/dynamics/EvaluatorResult.re
  src/hazelcore/dynamics/EvaluatorResult.rei
  src/hazelweb/Hazel.re
  src/hazelweb/ModelAction.re
  src/hazelweb/State.re
  src/hazelweb/Update.re
  src/hazelweb/Worker.re
  src/hazelweb/dune
  src/hazelweb/gui/ContextInspector.re
  src/hazelweb/gui/ContextInspector.rei
  src/hazelweb/gui/Page.re
  src/hazelweb/model/Model.re
  src/hazelweb/model/Model.rei
  src/hazelweb/model/ModelResult.re
  src/hazelweb/model/Program.rei
  src/hazelweb/model/ProgramEvaluator.re
  src/hazelweb/model/ProgramEvaluator.rei
  src/hazelweb/model/ProgramResult.re
  src/hazelweb/model/ProgramResult.rei
  src/hazelweb/util/Delay.re
  src/hazelweb/util/Delay.rei
  src/hazelweb/util/Lwt_timed_js.re
  src/hazelweb/util/Lwt_timed_js.rei
  src/hazelweb/util/Lwt_timed_pool_js.re
  src/hazelweb/util/Lwt_timed_pool_js.rei
  src/hazelweb/util/WebWorker.re
  src/hazelweb/util/WebWorker.rei
  src/hazelweb/util/WebWorkerPool.re
  src/hazelweb/util/WebWorkerPool.rei
  src/hazelweb/www/dune
  src/lwtutil/Lwt_observable.re
  src/lwtutil/Lwt_observable.rei
  src/lwtutil/Lwt_timed.re
  src/lwtutil/Lwt_timed.rei
  src/lwtutil/Lwt_timed_pool.re
  src/lwtutil/Lwt_timed_pool.rei
  src/lwtutil/Test.re
  src/lwtutil/dune
Labels: needs-polish

#734 Introduce last-touched timestamps + use for history-sensitive indentation in incomplete segments
  src/core/Measured.re
  src/core/tiles/Segment.re
  src/core/zipper/Editor.re
  src/core/zipper/IncompleteBidelim.re
  src/core/zipper/Time.re
  src/core/zipper/Touched.re
  src/core/zipper/Zipper.re
  src/core/zipper/action/Action.re
  src/core/zipper/action/Caret.re
  src/core/zipper/action/Destruct.re
  src/core/zipper/action/Effect.re
  src/core/zipper/action/Insert.re
  src/core/zipper/action/Move.re
  src/core/zipper/action/Perform.re
  src/core/zipper/action/Select.re
  src/web/ActionHistory.re
  src/web/Example.re
  src/web/FailedInput.re
  src/web/LocalStorage.re
  src/web/Log.re
  src/web/Model.re
  src/web/Study.re
  src/web/Update.re
  src/web/view/BackpackView.re
  src/web/view/Deco.re
  src/web/view/Editor.re
  src/web/view/Page.re
  src/web/view/Printer.re
  src/web/view/SchoolMode.re
  src/web/view/SimpleMode.re
  src/web/view/dec/PieceDec.re
  src/web/www/style.css
Labels: haz3l
