Repository hazelgrove/hazel, pull requests merged in 2023-06, with the labels that each got.

#1010 Add jump-to-tests
  src/haz3lschool/SchoolExercise.re
  src/haz3lweb/Grading.re
  src/haz3lweb/Update.re
  src/haz3lweb/UpdateAction.re
  src/haz3lweb/view/SchoolMode.re
  src/haz3lweb/view/TestView.re
Labels: needs-polish

#1049 remove assumption that certain things only appear in closures when printing
  src/haz3lcore/dynamics/EvaluatorPost.rei
  src/haz3lweb/view/dhcode/layout/DHDoc_Exp.re
Labels: bug

#1054 remove err-status field in DHExp ListLit
  src/haz3lcore/dynamics/DH.re
  src/haz3lcore/dynamics/Evaluator.re
  src/haz3lcore/dynamics/EvaluatorPost.re
  src/haz3lcore/dynamics/ListErrStatus.re
  src/haz3lcore/dynamics/Substitution.re
  src/haz3lcore/dynamics/elaborator.re
  src/haz3lweb/view/dhcode/layout/DHDoc_Exp.re
Labels: cleanup

#1053 Cleanup: Fixed directory naming
  INSTALL.md
Labels: documentation
