Repository hazelgrove/hazel, pull requests merged in 2023-08, with the labels that each got.

#1081 Update Install Documentation
  INSTALL.md
Labels: documentation

#1039 School mode and school exercise documentation
  src/haz3lcore/prog/ModelResults.re
  src/haz3lschool/Exercise.re
  src/haz3lweb/Editors.re
  src/haz3lweb/Update.re
Labels: documentation

#1037 Syntax checker for school mode
  src/haz3lschool/Exercise.re
  src/haz3lschool/Gradescope.re
  src/haz3lschool/Grading.re
  src/haz3lschool/SyntaxTest.re
  src/haz3lweb/Grading.re
  src/haz3lweb/exercises/Ex_OddlyRecursive.ml
  src/haz3lweb/exercises/Ex_RecursiveFibonacci.ml
  src/haz3lweb/view/ExerciseMode.re
  src/haz3lweb/www/style.css
Labels: needs-polish

#1066 Replace integer counter IDs with random 128bit UUIDs
  opam.export
  src/haz3lcore/Measured.re
  src/haz3lcore/dune
  src/haz3lcore/dynamics/Elaborator.re
  src/haz3lcore/dynamics/HoleInstance.re
  src/haz3lcore/dynamics/KeywordID.re
  src/haz3lcore/dynamics/MetaVar.re
  src/haz3lcore/dynamics/MetaVar.rei
  src/haz3lcore/dynamics/MetaVarMap.re
  src/haz3lcore/prog/Interface.re
  src/haz3lcore/statics/TypBase.re
  src/haz3lcore/tiles/Grout.re
  src/haz3lcore/tiles/Id.re
  src/haz3lcore/tiles/Segment.re
  src/haz3lcore/zipper/Ancestors.re
  src/haz3lcore/zipper/EditorUtil.re
  src/haz3lcore/zipper/IdGen.re
  src/haz3lcore/zipper/PersistentZipper.re
  src/haz3lcore/zipper/Printer.re
  src/haz3lcore/zipper/Relatives.re
  src/haz3lcore/zipper/Siblings.re
  src/haz3lcore/zipper/Zipper.re
  src/haz3lcore/zipper/action/Destruct.re
  src/haz3lcore/zipper/action/Indicated.re
  src/haz3lcore/zipper/action/Insert.re
  src/haz3lcore/zipper/action/Perform.re
  src/haz3lschool/Exercise.re
  src/haz3lweb/Benchmark.re
  src/haz3lweb/ColorSteps.re
  src/haz3lweb/Editors.re
  src/haz3lweb/Example.re
  src/haz3lweb/Grading.re
  src/haz3lweb/Init.ml
  src/haz3lweb/Keyboard.re
  src/haz3lweb/LangDocMessages.re
  src/haz3lweb/Log.re
  src/haz3lweb/ScratchSlide.re
  src/haz3lweb/ScratchSlidesInit.re
  src/haz3lweb/SerializedExamples.ml
  src/haz3lweb/Store.re
  src/haz3lweb/Update.re
  src/haz3lweb/UpdateAction.re
  src/haz3lweb/exercises/Ex_OddlyRecursive.ml
  src/haz3lweb/exercises/Ex_RecursiveFibonacci.ml
  src/haz3lweb/view/CursorInspector.re
  src/haz3lweb/view/Deco.re
  src/haz3lweb/view/LangDoc.re
  src/haz3lweb/view/TestView.re
  src/haz3lweb/view/dhcode/DHCode.re
  src/haz3lweb/view/dhcode/layout/DHDoc_Util.re
  src/haz3lweb/www/style.css
Labels: needs-merge
