Repository hazelgrove/hazel, pull requests merged in 2024-02, with the labels that each got.

#1189 ExplainThis highlighting on hover
  src/haz3lcore/zipper/Zipper.re
  src/haz3lcore/zipper/action/Action.re
  src/haz3lcore/zipper/action/Perform.re
  src/haz3lcore/zipper/action/Select.re
  src/haz3lweb/Init.ml
  src/haz3lweb/Settings.re
  src/haz3lweb/Update.re
  src/haz3lweb/UpdateAction.re
  src/haz3lweb/explainthis/ExplainThisModel.re
  src/haz3lweb/explainthis/ExplainThisUpdate.re
  src/haz3lweb/view/Cell.re
  src/haz3lweb/view/CursorInspector.re
  src/haz3lweb/view/Deco.re
  src/haz3lweb/view/ExerciseMode.re
  src/haz3lweb/view/ExplainThis.re
  src/haz3lweb/view/NutMenu.re
  src/haz3lweb/view/ScratchMode.re
  src/haz3lweb/www/style.css
Labels: needs-polish

#1166 Cached statics
  src/haz3lcore/dynamics/EvaluatorPost.re
  src/haz3lcore/dynamics/EvaluatorPost.rei
  src/haz3lcore/dynamics/TestResults.re
  src/haz3lcore/prog/CachedStatics.re
  src/haz3lcore/prog/Interface.re
  src/haz3lcore/prog/ModelResult.re
  src/haz3lcore/prog/ProgramResult.re
  src/haz3lcore/prog/ProgramResult.rei
  src/haz3lcore/statics/Statics.re
  src/haz3lcore/tiles/Segment.re
  src/haz3lcore/zipper/Editor.re
  src/haz3lcore/zipper/EditorUtil.re
  src/haz3lcore/zipper/Selection.re
  src/haz3lcore/zipper/Zipper.re
  src/haz3lschool/Exercise.re
  src/haz3lschool/Grading.re
  src/haz3lweb/DebugAction.re
  src/haz3lweb/DebugConsole.re
  src/haz3lweb/Editors.re
  src/haz3lweb/Grading.re
  src/haz3lweb/Main.re
  src/haz3lweb/Model.re
  src/haz3lweb/ScratchSlide.re
  src/haz3lweb/Settings.re
  src/haz3lweb/Update.re
  src/haz3lweb/UpdateAction.re
  src/haz3lweb/explainthis/data/CaseExp.re
  src/haz3lweb/explainthis/data/FunctionExp.re
  src/haz3lweb/explainthis/data/LetExp.re
  src/haz3lweb/view/Cell.re
  src/haz3lweb/view/Code.re
  src/haz3lweb/view/CursorInspector.re
  src/haz3lweb/view/DebugMode.re
  src/haz3lweb/view/Deco.re
  src/haz3lweb/view/EditorModeView.re
  src/haz3lweb/view/ExerciseMode.re
  src/haz3lweb/view/ExplainThis.re
  src/haz3lweb/view/NutMenu.re
  src/haz3lweb/view/Page.re
  src/haz3lweb/view/ScratchMode.re
  src/haz3lweb/view/StepperView.re
  src/haz3lweb/view/TestView.re
  src/haz3lweb/view/dhcode/DHCode.re
  src/haz3lweb/www/style.css
Labels: needs-polish

#1158 Re-enable workers
  src/haz3lcore/dynamics/DH.re
  src/haz3lcore/dynamics/Stepper.re
  src/haz3lcore/prog/Interface.re
  src/haz3lcore/prog/ModelResult.re
  src/haz3lcore/prog/ModelResults.re
  src/haz3lcore/prog/ProgramEvaluatorError.re
  src/haz3lcore/prog/ProgramResult.re
  src/haz3lschool/dune
  src/haz3lweb/Keyboard.re
  src/haz3lweb/Log.re
  src/haz3lweb/Main.re
  src/haz3lweb/Model.re
  src/haz3lweb/ProgramEvaluator.re
  src/haz3lweb/ProgramEvaluator.rei
  src/haz3lweb/State.re
  src/haz3lweb/Update.re
  src/haz3lweb/UpdateAction.re
  src/haz3lweb/Worker.re
  src/haz3lweb/dune
  src/haz3lweb/util/Delay.re
  src/haz3lweb/util/Delay.rei
  src/haz3lweb/util/Lwt_timed_js.re
  src/haz3lweb/util/Lwt_timed_js.rei
  src/haz3lweb/util/Lwt_timed_pool_js.re
  src/haz3lweb/util/Lwt_timed_pool_js.rei
  src/haz3lweb/util/WebWorker.re
  src/haz3lweb/util/WebWorker.rei
  src/haz3lweb/util/WebWorkerPool.re
  src/haz3lweb/util/WebWorkerPool.rei
  src/haz3lweb/util/WorkerClient.re
  src/haz3lweb/util/WorkerServer.re
  src/haz3lweb/view/Cell.re
  src/haz3lweb/view/ExerciseMode.re
  src/haz3lweb/view/ScratchMode.re
  src/haz3lweb/view/StepperView.re
  src/haz3lweb/www/style.css
  src/lwtutil/Lwt_observable.re
  src/lwtutil/Lwt_observable.rei
  src/lwtutil/Lwt_timed.re
  src/lwtutil/Lwt_timed.rei
  src/lwtutil/Lwt_timed_pool.re
  src/lwtutil/Lwt_timed_pool.rei
  src/lwtutil/Test.re
  src/lwtutil/dune
Labels: needs-polish

#1132 Empty hole casting fix
  src/haz3lcore/dynamics/Elaborator.re
Labels: in-development

#1123 analytic constructor casting fix
  src/haz3lcore/dynamics/Elaborator.re
Labels: in-development

#1124 Case expression redundancy checking
  src/haz3lcore/dynamics/Elaborator.re
  src/haz3lcore/statics/Info.re
  src/haz3lcore/statics/Self.re
  src/haz3lcore/statics/Statics.re
  src/haz3lweb/view/CursorInspector.re
Labels: pending

#1202 DHExp error holes fixes
  src/haz3lweb/view/dhcode/Decoration_common.re
  src/haz3lweb/view/dhcode/layout/DHDoc_Exp.re
  src/haz3lweb/www/style.css
Labels: bug, needs-polish

#1214 Make stepper change on elab change
  src/haz3lcore/prog/ModelResults.re
  src/haz3lweb/Update.re
  src/haz3lweb/www/style.css
Labels: bug, critical
