Repository hazelgrove/hazel, pull requests merged in 2025-07, with the labels that each got.

#1781 Adjusting some selection movement behavior
  src/haz3lcore/zipper/Printer.re
  src/haz3lcore/zipper/Zipper.re
  src/haz3lcore/zipper/action/Move.re
  src/util/OptUtil.re
  test/Test_Editing.re
Labels: editing

#1267 Polymorphic equality
  src/haz3lcore/TyDi/ErrorPrint.re
  src/haz3lcore/lang/MakeTerm.re
  src/haz3lcore/lang/Precedence.re
  src/language/builtins/BuiltinsList.re
  src/language/dynamics/DHExp.re
  src/language/dynamics/transition/Transition.re
  src/language/proof/Axioms.re
  src/language/proof/ProofRule.re
  src/language/statics/Info.re
  src/language/statics/Self.re
  src/language/statics/Statics.re
  src/language/term/InvalidOperationError.re
  src/language/term/Operators.re
  src/language/term/Typ.re
  src/menhirParser/AST.re
  src/menhirParser/Conversion.re
  src/menhirParser/Lexer.mll
  src/menhirParser/Parser.mly
  src/web/app/explainthis/ExplainThis.re
  src/web/app/explainthis/ExplainThisForm.re
  src/web/app/explainthis/data/OpExp.re
  src/web/app/inspector/CursorInspector.re
  test/Test_Elaboration.re
  test/Test_Menhir.re
  test/evaluator/Test_Evaluator.re
  test/evaluator/Test_Evaluator_Poly_Equal.re
  test/statics/Test_Statics_Polymorphism.re
Labels: starter-project, in-development

#1799 Add ToggleFocus action
  src/haz3lcore/zipper/Zipper.re
  src/haz3lcore/zipper/action/Action.re
  src/haz3lcore/zipper/action/Perform.re
  src/web/app/editors/code/CodeEditable.re
  src/web/app/input/Shortcut.re
Labels: enhancement, editing
